// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjHb2XnKRQzemDD-p6eEmyfKeNLMpIMw',
    appId: '1:340490911028:web:0a69959ab628b04dacf961',
    messagingSenderId: '340490911028',
    projectId: 'marihan-store',
    authDomain: 'marihan-store.firebaseapp.com',
    storageBucket: 'marihan-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzNIxiZoyMejf8QYTdtxuD08tkGyIo-Bc',
    appId: '1:340490911028:android:acabbd627e819414acf961',
    messagingSenderId: '340490911028',
    projectId: 'marihan-store',
    storageBucket: 'marihan-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2vHoZzr3oeBiHhMwUzqvPcSqMQEUya4',
    appId: '1:340490911028:ios:3941ca7d1b8da42bacf961',
    messagingSenderId: '340490911028',
    projectId: 'marihan-store',
    storageBucket: 'marihan-store.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );
}
